### PR TITLE
allowing before_execution_proc to be in the instance.

### PR DESCRIPTION
**Pull request by fribeiro**
The ideia is to allowing Resource to have it's own before_execution_proc in addition to the one that's provided by the class. Let me know what you think.

thank you.

### CODE REVIEW

**Comment by brbrr** [comment]
Could it be merged? looking for such functionality

**Comment by oschreib** [comment]
@ab any chance to merge this? (open > 1yr), and we really want this functionality.

**Comment by simon3z** [comment]
@ab any update on the status of this issue? do you need help to get it fixed?

**Comment by ab** [comment]
Thanks! I ended up taking a slightly different approach here. You can set a `:before_execution_proc` as an option to any `Request` or `Resource` object.

**Pull request closed without merging**
