### PR TITLE
Allow `http-accept` 2.x.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
Maybe the best solution is conditionally requiring `http/accept`.

**Comment by joshRpowell** [comment]
see #719 and close this

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
is it possible to have some fucking news?

**Comment by ioquatix** [comment]
I give up.

**Pull request closed without merging**
