### PR TITLE
Also pass timeout parameters to redirected request.

### PR DESCRIPTION
**Pull request by nightscape**
Hi!

When following a redirection, the timeout parameters get lost in the new request.

I would have added a test, but I'm not sure how, as currently all tests are using WebMocks stub_request and I have no clue how to test for additional parameters with that.

If you have an idea how to test that, I'll add a corresponding spec.

Thanks!
  Martin

### CODE REVIEW

**Comment by ab** [comment]
I haven't been able to reproduce this issue. If I understand correctly, args is already passed through by the original request and should include timeout and other parameters.
https://github.com/rest-client/rest-client/blob/8e89ccc5d5a4801d5424ab9ad511573d2ef94d55/lib/restclient/request.rb#L530

Do you have an example usage where you hit the problem?

**Comment by nightscape** [comment]
Yes, the args are passed correctly from the request to the response.
But if you then call ```response. follow_redirection``` the args are not copied from the response to the new request (see the change from this PR).
The use case is the following: We are GETting from a URL which might take longer to load and therefore need a custom timeout. The response to the GET can also be a redirect, for which the same timeout should be applied. Currently, this does not work, the second request will timeout too early.

**Comment by ab** [comment]
@nightscape I'm still not able to reproduce this. The `args` used in the redirection request [1] is actually an instance variable created from the args of the original request. [2]

The existing code is _overriding_ the existing options with new cookies and user/password for the new redirected URI.

If you add a `puts` for debugging at the top of RestClient::Request#initialize, you should see that args does contain the timeout.

[1] https://github.com/rest-client/rest-client/blob/23210393/lib/restclient/abstract_response.rb#L83
[2] https://github.com/rest-client/rest-client/blob/23210393/lib/restclient/request.rb#L536

**Comment by nightscape** [comment]
Ok, got it. I overlooked that args are not constructed here, but have already been set before.
Then maybe the problem at that time was a random fail.
Unfortunately I also can't find the code for the original problem.
I'll close this PR, sorry for wasting your time...

**Comment by ab** [comment]
No worries, it was a good opportunity for me to get to know this section of the code. I think there's a lurking minor security problem in the way cookies are handled on redirects...

**Pull request closed without merging**
