### PR TITLE
Adding Support for Digest Authentication

### PR DESCRIPTION
**Pull request by MaximilianMeister**
addresses: https://github.com/rest-client/rest-client/issues/102
supersedes: https://github.com/rest-client/rest-client/pull/122

### CODE REVIEW

**Comment by rsalevsky** [comment]
@ab Do you think it is possible to release this with 2.1.0 or sooner? We depend on this feature in one of our products.

**Comment by krtschmr** [comment]
merge?!

**Comment by MaximilianMeister** [comment]
rebased

unit tests succeed, only rubocop fails in many files that were not touched in this PR

**Comment by joshatozfx** [comment]
Anyone know of another Rest client for ruby that can do digest?

**Comment by MaximilianMeister** [comment]
> Anyone know of another Rest client for ruby that can do digest?

@joshatozfx you can use [httparty](https://github.com/jnunemaker/httparty) as an alternative with their [DigestAuthenticator](http://www.rubydoc.info/github/jnunemaker/httparty/Net/HTTPHeader/DigestAuthenticator)

**Comment by joshatozfx** [comment]
Thanks Max, the httparty gem seems to work for me. looking forward to having this merge done and i can use this gem again :-)

**Comment by MaximilianMeister** [comment]
i expect no more reviews here. closing

**Pull request closed without merging**
