### PR TITLE
detect JSON documents in multipart form data and set content-type

### PR DESCRIPTION
**Pull request by jlambert121**

### CODE REVIEW

**Comment by ab** [comment]
The current code chooses content type based on a `content_type` method or on file extensions from the MIME types registry. It seems super unreliable and surprising to guess at the content type based on the file content. For instance, a `foo.txt` file containing the text `[]` would suddenly be rendered as `application/json` rather than `text/plain`.

Where would we stop the content sniffing? Should we also attempt to parse all files as YAML? As XML? How do we tell the difference between a JSON document and a YAML document that's using the subset that is valid JSON?

**Comment by jlambert121** [comment]
Except the current method doesn't work for multipart if you just have an object to serialize instead of transferring a file....

**Comment by ab** [comment]
This isn't an area of the code I'm super familiar with. Could you provide an example use case so I can better understand?

**Comment by jlambert121** [comment]
Quick copy/paste/hack of what caused me to submit this PR:

```ruby
        data = { :param1 => value, :param2 => value2 }
        request = RestClient::Request.new(
          :method => :post,
          :url => uri,
          :headers => { 'User-Agent' => VERSION, 'Accept' => 'application/json' },
          :payload => { :multipart => true, :event => data.to_json, :file => File.new(file, 'rb') }
        )
        response = request.execute
```

**Comment by ab** [comment]
I think what you actually want here is a way to specify the content-type for each multipart piece: https://github.com/rest-client/rest-client/pull/222

**Pull request closed without merging**
